# -*- coding: utf-8 -*-
"""
Acceso a PostgreSQL: pool de conexiones, helpers de consulta y esquema.

Conexión por variables de entorno:
  - DATABASE_URL  (ej: postgresql://user:pass@host:5432/dbname?sslmode=require)
  o bien PGHOST PGUSER PGPASSWORD PGDATABASE PGPORT PGSSLMODE
Azure Database for PostgreSQL Flexible Server exige TLS -> sslmode=require por defecto.

Las consultas usan los placeholders nativos de psycopg (%s / %(nombre)s) y las filas
llegan como dict. Para listas: `col = ANY(%s)` con una lista de Python.
"""
import atexit
import datetime
import os
from contextlib import contextmanager

import psycopg
from psycopg.conninfo import make_conninfo
from psycopg.rows import dict_row
from psycopg_pool import ConnectionPool

IntegrityError = psycopg.IntegrityError

# Hora de Perú (GMT-5, sin horario de verano): el servidor en Azure corre en UTC,
# así las fechas de creación/última revisión no se adelantan un día.
LIMA_TZ = datetime.timezone(datetime.timedelta(hours=-5))


def today():
    return datetime.datetime.now(LIMA_TZ).date().isoformat()


def now():
    return datetime.datetime.now(LIMA_TZ).replace(tzinfo=None).isoformat(timespec="seconds")


def _conninfo():
    url = os.environ.get("DATABASE_URL")
    if url:
        return url
    if not os.environ.get("PGHOST"):
        raise RuntimeError(
            "Falta configuración de base de datos. Define DATABASE_URL o "
            "PGHOST/PGUSER/PGPASSWORD/PGDATABASE en las variables de entorno.")
    return make_conninfo(
        host=os.environ["PGHOST"],
        port=os.environ.get("PGPORT", "5432"),
        dbname=os.environ.get("PGDATABASE", "postgres"),
        user=os.environ.get("PGUSER", ""),
        password=os.environ.get("PGPASSWORD", ""),
        sslmode=os.environ.get("PGSSLMODE", "require"))


_pool = None


def pool():
    global _pool
    if _pool is None:
        _pool = ConnectionPool(_conninfo(), min_size=1,
                               max_size=int(os.environ.get("PG_POOL_MAX", "10")),
                               kwargs={"row_factory": dict_row}, open=True)
        atexit.register(close)
    return _pool


def close():
    """Cierra el pool (al terminar scripts o el servidor)."""
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None


@contextmanager
def tx():
    """Conexión del pool en una transacción: commit al salir, rollback si hay excepción."""
    with pool().connection() as con:
        yield con


def rows(sql, params=None):
    with tx() as con:
        return con.execute(sql, params).fetchall()


def one(sql, params=None):
    with tx() as con:
        return con.execute(sql, params).fetchone()


def scalar(sql, params=None):
    r = one(sql, params)
    return next(iter(r.values())) if r else None


def run(sql, params=None):
    """Ejecuta un INSERT/UPDATE/DELETE y devuelve las filas afectadas."""
    with tx() as con:
        return con.execute(sql, params).rowcount


# --------------------------- esquema ---------------------------
# Las fechas se guardan como TEXT 'YYYY-MM-DD[THH:MM:SS]' (comparables como cadenas).
_TS = "to_char(now(),'YYYY-MM-DD\"T\"HH24:MI:SS')"
SCHEMA = [
    f"""CREATE TABLE IF NOT EXISTS comunicados(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      n TEXT, titulo TEXT NOT NULL, categoria TEXT,
      fecha_recepcion TEXT, fecha_limite TEXT,
      resumen TEXT, fuente TEXT, archivo TEXT,
      estado TEXT, responsable TEXT,
      ultima_actualizacion TEXT, proxima_actualizacion TEXT,
      observaciones TEXT, kql TEXT,
      origen TEXT DEFAULT 'excel',
      afecta_todas INTEGER DEFAULT 0,
      archivado INTEGER DEFAULT 0,
      created_at TEXT DEFAULT ({_TS}))""",
    f"""CREATE TABLE IF NOT EXISTS clientes(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nombre TEXT UNIQUE NOT NULL, ext_id TEXT,
      archivado INTEGER DEFAULT 0,
      created_at TEXT DEFAULT ({_TS}))""",
    f"""CREATE TABLE IF NOT EXISTS suscripciones(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      cliente_id BIGINT NOT NULL REFERENCES clientes(id) ON DELETE CASCADE,
      nombre TEXT, sub_id TEXT,
      created_at TEXT DEFAULT ({_TS}))""",
    f"""CREATE TABLE IF NOT EXISTS inventarios(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      comunicado_id BIGINT NOT NULL REFERENCES comunicados(id) ON DELETE CASCADE,
      fecha TEXT, kql TEXT,
      created_at TEXT DEFAULT ({_TS}))""",
    f"""CREATE TABLE IF NOT EXISTS recursos(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      comunicado_id BIGINT NOT NULL REFERENCES comunicados(id) ON DELETE CASCADE,
      hoja TEXT, cliente TEXT,
      suscripcion TEXT, suscripcion_id TEXT,
      grupo_recurso TEXT, nombre_recurso TEXT,
      gestor TEXT, estado TEXT, extra TEXT,
      revisado INTEGER DEFAULT 0, revisado_por TEXT, revisado_at TEXT,
      notas TEXT,
      created_at TEXT DEFAULT ({_TS}),
      inventario_id BIGINT)""",
    f"""CREATE TABLE IF NOT EXISTS miembros(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      correo TEXT UNIQUE NOT NULL,
      nombre TEXT, apellido TEXT, pwd TEXT,
      created_at TEXT DEFAULT ({_TS}))""",
    """CREATE TABLE IF NOT EXISTS papelera(
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      comunicado_id BIGINT, titulo TEXT, datos TEXT,
      eliminado_por TEXT, eliminado_at TEXT)""",
    # Sesiones de login: se guarda el SHA-256 del token, nunca el token.
    """CREATE TABLE IF NOT EXISTS sesiones(
      token_hash TEXT PRIMARY KEY,
      miembro_id BIGINT NOT NULL REFERENCES miembros(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
      expires_at TIMESTAMPTZ NOT NULL)""",
    "CREATE INDEX IF NOT EXISTS ix_inv_com ON inventarios(comunicado_id)",
    "CREATE INDEX IF NOT EXISTS ix_rec_com ON recursos(comunicado_id)",
    "CREATE INDEX IF NOT EXISTS ix_rec_sub ON recursos(suscripcion)",
    "CREATE INDEX IF NOT EXISTS ix_rec_rev ON recursos(revisado)",
    "CREATE INDEX IF NOT EXISTS ix_rec_inv ON recursos(inventario_id)",
    "CREATE INDEX IF NOT EXISTS ix_sus_cli ON suscripciones(cliente_id)",
    "CREATE INDEX IF NOT EXISTS ix_ses_miem ON sesiones(miembro_id)",
    # migraciones (idempotentes) de bases creadas con versiones anteriores
    "ALTER TABLE comunicados ADD COLUMN IF NOT EXISTS afecta_todas INTEGER DEFAULT 0",
    "ALTER TABLE comunicados ADD COLUMN IF NOT EXISTS archivado INTEGER DEFAULT 0",
    "ALTER TABLE inventarios DROP COLUMN IF EXISTS nota",
    "ALTER TABLE clientes ADD COLUMN IF NOT EXISTS archivado INTEGER DEFAULT 0",
    "ALTER TABLE miembros ADD COLUMN IF NOT EXISTS rol TEXT DEFAULT 'editor'",
    "ALTER TABLE miembros ADD COLUMN IF NOT EXISTS debe_cambiar INTEGER DEFAULT 0",
    # Recursos SOLO del último lote de cada comunicado: base de todos los conteos,
    # % y estados. Los lotes anteriores quedan como historial.
    """CREATE OR REPLACE VIEW recursos_ult AS
      SELECT r.* FROM recursos r
      JOIN (SELECT DISTINCT ON (comunicado_id) id FROM inventarios
            ORDER BY comunicado_id, created_at DESC, id DESC) l ON l.id = r.inventario_id""",
]


def ensure_schema(admin_correo=None):
    """Crea/migra el esquema (idempotente) y garantiza que exista al menos un admin:
    si no hay ninguno se promueve a `admin_correo` o, si no existe, al miembro más antiguo."""
    with tx() as con:
        con.execute("SELECT pg_advisory_xact_lock(84210731)")   # varios workers arrancando a la vez
        for stmt in SCHEMA:
            con.execute(stmt)
        if not con.execute("SELECT 1 FROM miembros WHERE rol='admin'").fetchone():
            row = None
            if admin_correo:
                row = con.execute("SELECT id FROM miembros WHERE correo=%s",
                                  (admin_correo.strip().lower(),)).fetchone()
            row = row or con.execute("SELECT id FROM miembros ORDER BY id LIMIT 1").fetchone()
            if row:
                con.execute("UPDATE miembros SET rol='admin' WHERE id=%s", (row["id"],))
